dataset:
  mnist:
    path: data/mnist
    train_pct: 0.8
    val_pct: 0.2

train:
  gpus: null
  early_stop: false
  run_test: false
  batch_size: 300
  max_epochs: 1000
  learning_rate: 0.001
  n_data_workers: 4
  train_percent: 1.0
  val_percent: 1.0
  resume_checkpoint: null

defaults:
  - network: small

